import { defineConfig } from 'oxfmt';
import type { OxfmtConfig, OxfmtOverrideConfig } from 'oxfmt';

const agentDocMarkdownPaths = [
  '.github/copilot-instructions.md',
  '.github/instructions/**/*.md',
  '.github/prompts/**/*.md',
  '.github/skills/**/*.md',
  '.windsurf/rules/**/*.md',
  '.cline/rules/**/*.md',
  '.ai/**/*.md',
  'CLAUDE.md',
  'CLAUDE.local.md',
  'AGENTS.md',
  'GEMINI.md',
  'COPILOT.md',
  'CONVENTIONS.md',
];

export default defineConfig({
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'lf',
  insertFinalNewline: true,
  objectWrap: 'preserve',
  printWidth: 110,
  quoteProps: 'consistent',
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  sortPackageJson: false,
  tabWidth: 2,
  useTabs: false,
  ignorePatterns: [
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/bin/**',
    '**/coverage/**',
    '**/.astro/**',
    '**/.turbo/**',
    '*.d.ts',
    '**/*.min.*',
    '**/*.map',
    '**/.claude/todos*',
    '**/.claude/settings*',
    '**/.github/workflows/**',
    '**/.github/ISSUE_TEMPLATE/**',
    '**/.github/PULL_REQUEST_TEMPLATE/**',
    '**/icons.generated.ts',
    '**/icons/index.ts',
    '**/icons/**/index.ts',
  ],
  overrides: [
    { files: ['*.json', '*.jsonc'], excludeFiles: [], options: { tabWidth: 2, trailingComma: 'none' } },
    {
      files: ['*.md', '*.mdx'],
      excludeFiles: agentDocMarkdownPaths,
      options: { embeddedLanguageFormatting: 'off', printWidth: 110, proseWrap: 'preserve' },
    },
    {
      files: agentDocMarkdownPaths,
      excludeFiles: [],
      options: { embeddedLanguageFormatting: 'off', printWidth: 180, proseWrap: 'preserve' },
    },
  ] satisfies OxfmtOverrideConfig[],
} satisfies OxfmtConfig);
